### ISSUE TITLE
On the road to PyScaffold 4.0 

### ISSUE THREAD

**Issue by abravalheri** [pyscaffold/pyscaffoldext-custom-extension#21]
I have created a new `pyscaffold-v4` branch containing the code prepared to run with v4.
The idea is to do the same for all the extensions (and hopefully having migrated this one first will help, so we can do a forced update + git difftool).

@FlorianWilhelm, I have noticed that you were working in a  `v0.6a1` tag. Will that v0.6 still be released (and in that case v0.7 will be the version compatible with PyScaffold v4)? Or the newest changes will be absorbed into a v0.6?

**Comment by FlorianWilhelm** [comment]
@abravalheri, having a `pyscaffold-v4` branch is a good idea. I once started working on a v0.6 release to make necessary changes for version 4.0 of PyScaffold but then stopped working on it a while ago. I think you could still reuse everything and use the version 0.6 for the necessary changes for the actual version 4.0 of PyScaffold, i.e. you can absorb it.

**Comment by abravalheri** [comment]
Update: the branch `pyscaffold-v4` was merged into master, following the latest changes in PyScaffold itself. The branch v3 now points to the latest version supporting v3.

**Comment by FlorianWilhelm** [comment]
This looks like it's resolved, thanks @abravalheri
