### ISSUE TITLE
Create files that are part of the .gitignore

### ISSUE THREAD

**Issue by cc-gb2** [pyscaffold/pyscaffoldext-custom-extension#41]
I'm trying to create a rather simple extension that creates a starting `.vscode/settings.json` for projects to initialise some basic vscode settings and that sort of thing. However, the `.vscode` folder is in the default `.gitignore` (which shouldn't change) so the `init_git` action will raise an error due to ignored files. See below: 
```
pyscaffold.exceptions.ShellCommandException: The following paths are ignored by one of your .gitignore files:
           .vscode/settings.json
           Use -f if you really want to add them.
```
I've tried add an action after the `init_git` action, but that doesn't create the file. Is there a way to do this?

**Comment by abravalheri** [comment]
Hi @cc-gb2, would it make sense to modify the contents of `.gitignore` with `!.vscode/settings.json`? Or is this a setting that should not be tracked via SCM?

> I've tried add an action after the init_git action, but that doesn't create the file. Is there a way to do this?

How exactly is this action, have you tried to simple write the file to the disk?

**Comment by abravalheri** [comment]
In v4, you can modify contents of existing files by doing:

```python
leaf = struct[".gitignore"]
old_contents, file_op = reify_leaf(leaf, opts)

new_contents = ...  # do something with old_contents

files = {".gitignore": (new_contents, file_op)}
return merge(struct, files), opts
```

`reify_leaf` is a function in `pyscaffold.structure`.

**Comment by cc-gb2** [comment]
I'd rather it wasn't tracked with SCM if possible, but more of something start repos off with. 

I'll have a look into this and will get back to you!

**Comment by cc-gb2** [comment]
Sorry for the response. I got it working literally took 2mins after you explained thanks a lot! I did the multi-file method as it seems more extenable for the future. For anyone else who sees it, I solved it with this:
```
class Vscode(Extension):
    """
    Pyscaffold Extenion for to configuring VSCode

    This creates a basic `settings.json` for the cretaed workspace. This is run after the "init_git"
    action so that the files are untracked by git.
    """

    def activate(self, actions: List[Action]) -> List[Action]:
        """Activate extension. See :obj:`pyscaffold.extension.Extension.activate`."""
        actions = self.register(actions, add_untracked_vscode_files, after="init_git")
        return actions


def add_untracked_vscode_files(struct: Structure, opts: ScaffoldOpts) -> ActionParams:
    """Add settings.json file"""

    # See https://pyscaffold.org/en/stable/api/pyscaffold.templates.html for templates
    settings_template = get_template("settings.json", relative_to=extension_templates)
    files: Structure = {
        ".vscode": {
            "settings.json": (settings_template, no_overwrite(create)),
        }
    }
    new_struct, opts = create_structure(files, opts, prefix=None)
    return merge(struct, new_struct), opts
```
