### ISSUE TITLE
Have an extension call other extensions

### ISSUE THREAD

**Issue by cc-gb2** [pyscaffold/pyscaffoldext-custom-extension#46]
Hiya,

I'm trying to write an extension that call other extensions, I've seen the the [include](https://pyscaffold.org/en/latest/api/pyscaffold.extensions.html#pyscaffold.extensions.include) command but I'm a confused on when I need to use it. Do I register it in the actions pipeline?

**Comment by abravalheri** [comment]
Hi @cc-gb2 maybe the following example works for you?

https://github.com/pyscaffold/pyscaffoldext-dsproject/blob/master/src/pyscaffoldext/dsproject/extension.py#L24

The include helper can be used from the augment_cli function, to activate multiple extensions at once from the CLI.

**Comment by abravalheri** [comment]
(The same example also shows an alternative approach that is directly calling the `extend` method of the other extension you want to wrap)

**Comment by cc-gb2** [comment]
That's really helpful thanks! Perfect demonstration of a couple of ways to do it.
