### ISSUE TITLE
new .template files are not being picked up in build/install

### ISSUE THREAD

**Issue by nickarini** [pyscaffold/pyscaffoldext-custom-extension#49]
When using custom-extension to generate a new extension i followed the examples, particularly the dsproject example. When I came to add .template files these are somehow not being picked up in the build/install and therefore my custom extension is failing with a 

`FileNotFoundError: [Errno 2] No such file or directory: '/opt/homebrew/lib/python3.9/site-packages/pyscaffoldext_generative-0.0.post1.dev1+g12e1872.d20220111-py3.9.egg/pyscaffoldext/generative/templates/lint_sh.template'`

Steps to reproduce:

OS: Macos Monterey v12.0 (M1)
Python: Python 3.9.9

I verified similar behaviour in the dsproject:

1, git clone dsproject

2, Add a new .py and a new .template file to the `src/pyscaffoldext/dsproject/templates` folder.

3, run `python3 setup.py install`

4, Check the generated SOURCES.txt file 

Expected: Both .py and .template files are added to this list

Actual: only the new .py file is added. 

In dsproject the pre-existing .template files are added as expected but I have been unable to find where this filter or these specific files are specified. Its very possible I am doing something wrong here but it isnt clear from the documentation which might benefit from an example of adding custom templates. 

Thanks. 

![CleanShot 2022-01-12 at 09 35 08](https://user-images.githubusercontent.com/8394877/149115824-555121b9-d5fe-4928-80c3-1058af7c94ca.png)

**Comment by abravalheri** [comment]
Hi @nickarini, thank you very much for bringing this topic up.

Could you try to `git add` the new file before trying to build the package? If it does not work could you also try to do a commit before trying again?

I have the impression that this is a setuptools-scm limitation, because it relies on `git ls-files` to find what to include...

**Comment by nickarini** [comment]
Hi @abravalheri. I created a new local branch, git add and commit which is failing:

![CleanShot 2022-01-12 at 10 06 37](https://user-images.githubusercontent.com/8394877/149119932-b3b18de2-1749-4bc7-9aa1-e5a62024058a.png)

**Comment by nickarini** [comment]
OK I think I got it to work. I had to switch from ssh to https in `.pre-commit-config.yaml` in order to get pre-commit to run (was ignoring my ssh key for some reason). Once this ran successfully I was able to rerun `python3 setup.py install` and this seems to have done the trick as I can now see the .template files in SOURCES.txt:
![CleanShot 2022-01-12 at 10 33 31](https://user-images.githubusercontent.com/8394877/149124409-b4f24bb4-7f23-4cf9-8a1b-5969b157ff63.png)

Thanks for your help. Is it worth adding a note to the documentation as this was far from clear? 

Best regards,

Nick

**Comment by FlorianWilhelm** [comment]
Thanks @nickarini,

right now we have in docs:

![image](https://user-images.githubusercontent.com/3184072/149126967-f235e437-3ba8-4c66-8b29-c42512cce30d.png)

I think we could make ``are tracked by Git`` bold and also change this part from a rubric to a headline to allow to link to it and show it in the content on the right-side-bar.

**Comment by abravalheri** [comment]
> I think we could make `are tracked by Git` bold and also change this part from a rubric to a headline to allow to link to it and show it in the content on the right-side-bar.

Maybe even mention `git ls-files` as a measure to try to debug this.

**Comment by abravalheri** [comment]
I added pyscaffold/pyscaffold#567 so we can track this documentation issue there. (Therefore I think I we can close this issue for now).

@nickarini regarding the SSH problems, please note that @FlorianWilhelm solved problems that appeared recently with the new version of `pre-commit` in the latest version of PyScaffold released yesterday. You might give it a try 😄

**Comment by nickarini** [comment]
Amazing. Thank you both for such a rapid response. I will indeed update and try the ssh issue. Just to also confirm I was able to make this work with my original generated extension so al good. Closing now. Thanks!
