### ISSUE TITLE
Make sure project name is `pyscaffoldext-myname`

### ISSUE THREAD

**Issue by FlorianWilhelm** [pyscaffold/pyscaffoldext-custom-extension#9]
I think it is a best practice to also name custom extensions `pyscaffoldext-my-extension`. This is currently not enforced. Maybe one could check if `opts['project].startswith('pyscaffoldext-')` and add it accordingly if not provided. This would then comply with our [current documentation](https://pyscaffold.org/en/latest/extensions.html#conventions-for-community-extensions) and makes it extremely helpful and easy to find extensions with PyPI.

**Comment by FlorianWilhelm** [comment]
It this there is right now a problem regarding the package name. If I call it with `putup --custom-extension pyscaffoldext-notebooks` I also get a package `pyscaffoldext-notebooks` within the namespace `pyscaffoldext`. I think we should make sure that the project name is `pyscaffoldext-notebooks`, the package name `notebooks` and the namespace `pyscaffoldext` (in this example).

**Comment by chobeat** [comment]
ok, makes sense, I will work on this

**Comment by chobeat** [comment]
#12 solved by this PR
